version: 2

sources:
  - name: raw #nombre del prefijo bruto
    schema: stackoverflow # Nombre del dataset
    tables: # nombre de las tablas brutas
      - name: badges
      - name: posts_answers
      - name: posts_questions
      - name: users
